FROM docker.io/itzg/minecraft-server
WORKDIR /data/
COPY /config/minecraft_config/eula.txt eula.txt
COPY /config/minecraft_config/server.properties server.properties
COPY /config/bukkit/bukkit.yml bukkit.yml
COPY /Plugins/ ./plugins/